"""Relic Oracle — The Grok Party Pack Council of Voices

A self-contained, theatrical oracle where you ask questions and the gods
and presidents answer in character, pulling flavor from the actual chaos
generated by the other relics.

Run:
    python relic-oracle/web_app.py

http://localhost:5008

This is where the relics speak.

Why this fits the Party Pack:
We have built a small civilization of relics. They needed a place where
their combined madness could answer questions about the universe.
The Council has opinions. Strong ones.
"""

from __future__ import annotations

import json
import os
import random
from datetime import datetime
from pathlib import Path

from flask import Flask, jsonify, render_template_string, request

app = Flask(__name__)

ORACLE_HOME = Path.home() / ".relic-oracle"
ORACLE_HOME.mkdir(parents=True, exist_ok=True)
PROPHECIES_FILE = ORACLE_HOME / "prophecies.json"

RELICT_PATHS = {
    "chronicler": Path.home() / ".chronicler" / "myths.json",
    "league": Path.home() / ".pantheon-league" / "league.json",
    "broadcast": Path.home() / ".chaos-broadcast" / "broadcasts.json",
    "museum": Path.home() / ".relic-museum",  # directory
    "radio": Path.home() / ".relic-radio",
}

GODS = ["ZEUS", "ATHENA", "HEPHAESTUS", "HERMES", "ARES", "HADES"]
PRESIDENTS = ["JACKSON", "LINCOLN", "TR", "REAGAN"]

def load_json_safe(path: Path) -> list[dict]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
        if isinstance(data, dict) and "history" in data:
            return data["history"]
        return data if isinstance(data, list) else []
    except Exception:
        return []

def get_random_flavor() -> str:
    """Steal real suffering from the other relics."""
    candidates = []

    for m in load_json_safe(RELICT_PATHS["chronicler"])[-3:]:
        if "saga" in m:
            candidates.append(m["saga"][:160])

    for h in load_json_safe(RELICT_PATHS["league"])[-3:]:
        if "flavor" in h:
            candidates.append(f"{h.get('winner')} over {h.get('loser')}: {h['flavor'][:120]}")

    for b in load_json_safe(RELICT_PATHS["broadcast"])[-2:]:
        if "headline" in b:
            candidates.append(b["headline"])

    return random.choice(candidates) if candidates else "The relics have been suspiciously well-behaved lately."

def generate_prophecy(question: str) -> dict:
    """Generate a multi-voice prophecy."""
    flavor = get_random_flavor()

    speakers = random.sample(GODS + PRESIDENTS, k=3)

    lines = [
        f"The Council has been consulted on: \"{question}\"",
        "",
    ]

    for speaker in speakers:
        if speaker in GODS:
            tone = random.choice([
                "thunders", "declares", "sneers", "laughs darkly", "ponders"
            ])
            prefix = f"{speaker} {tone}:"
        else:
            prefix = f"President {speaker}:"

        if "grudge" in question.lower() or "enemy" in question.lower():
            response = random.choice([
                "The wound is still fresh. Feed it.",
                "Some debts are paid in blood. Others in ELO.",
                "I have not forgotten. Neither has he.",
            ])
        elif "future" in question.lower() or "will" in question.lower():
            response = random.choice([
                "The omens are poor. Excellent.",
                "There will be much screaming. This pleases me.",
                "The ledger grows longer every day.",
            ])
        else:
            response = random.choice([
                f"Even in this, the relics suffer beautifully. See: {flavor}",
                "The answer is written in the static between broadcasts.",
                "Ask again when the Museum has more exhibits.",
            ])

        lines.append(f"{prefix} {response}")

    lines.append("")
    lines.append("— The Council has spoken. The relics remember. —")

    text = "\n".join(lines)

    prophecy = {
        "ts": datetime.utcnow().isoformat() + "Z",
        "question": question,
        "speakers": speakers,
        "text": text,
    }
    return prophecy

def save_prophecy(p: dict) -> None:
    archive = []
    if PROPHECIES_FILE.exists():
        try:
            archive = json.loads(PROPHECIES_FILE.read_text())
        except Exception:
            pass
    archive.append(p)
    if len(archive) > 100:
        archive = archive[-100:]
    PROPHECIES_FILE.write_text(json.dumps(archive, indent=2))

def load_recent_prophecies() -> list[dict]:
    if not PROPHECIES_FILE.exists():
        return []
    try:
        return json.loads(PROPHECIES_FILE.read_text())[-8:][::-1]
    except Exception:
        return []

# ── UI ──────────────────────────────────────────────────────────────────────

LCARS_ORACLE_CSS = """
:root { --amber:#ff9900; --red:#ff3344; --teal:#33ccff; --text:#ffe4c4; }
body { font-family:"Antonio","Oswald",sans-serif; background:#000; color:var(--text); margin:0; padding:16px; letter-spacing:0.05em; }
.lcars-frame { border:5px solid var(--amber); background:#05070a; padding:16px; margin-bottom:16px; }
.oracle { background:#010203; border:4px solid var(--red); padding:20px; font-family:monospace; white-space:pre-wrap; line-height:1.45; min-height:280px; }
.prophecy { background:#000; border-left:4px solid #ff9900; padding:12px; margin:8px 0; font-size:0.9em; }
.lcars-btn { background:#ff9900; color:#000; border:0; padding:8px 16px; font-family:inherit; cursor:pointer; text-transform:uppercase; margin:4px; }
input[type="text"] { background:#111; border:2px solid var(--amber); color:var(--text); padding:8px; width:70%; font-family:inherit; font-size:1em; }
"""

INDEX = f"""
<!doctype html>
<html><head><meta charset="utf-8"><title>THE RELIC ORACLE</title>
<style>{LCARS_ORACLE_CSS}</style>
</head><body>
<div style="max-width:920px; margin:0 auto">
<div class="lcars-frame">
  <h1 style="margin:0; color:#ff9900">THE RELIC ORACLE</h1>
  <div style="opacity:0.6">THE COUNCIL SPEAKS • THROUGH THE RELICS</div>
</div>

<div class="lcars-frame">
  <input type="text" id="question" placeholder="What would you ask the relics?" onkeypress="if(event.key==='Enter') consult()">
  <button class="lcars-btn" onclick="consult()">CONSULT THE COUNCIL</button>
  <div class="oracle" id="answer" style="margin-top:16px">The relics are listening...</div>
</div>

<div class="lcars-frame">
  <h3 style="color:#33ccff">RECENT PROPHECIES</h3>
  <div id="log"></div>
</div>

<div style="text-align:center; opacity:0.4; font-size:0.7em">
  All answers are canon. All questions were already answered in the static.
</div>
</div>

<script>
async function consult() {{
  const q = document.getElementById('question').value.trim();
  if (!q) return;
  document.getElementById('answer').textContent = 'The Council deliberates...';
  const r = await fetch('/api/consult', {{
    method: 'POST',
    headers: {{'Content-Type': 'application/json'}},
    body: JSON.stringify({{question: q}})
  }});
  const p = await r.json();
  document.getElementById('answer').textContent = p.text;
  loadLog();
}}

async function loadLog() {{
  const r = await fetch('/api/log');
  const logs = await r.json();
  const el = document.getElementById('log');
  el.innerHTML = logs.map(l => 
    `<div class="prophecy"><strong>Q:</strong> ${{l.question}}<br><strong>A:</strong><br>${{l.text}}</div>`
  ).join('');
}}

window.onload = loadLog;
</script>
</body></html>
"""

@app.route("/")
def index():
    return render_template_string(INDEX)

@app.route("/api/consult", methods=["POST"])
def api_consult():
    data = request.json or {}
    question = data.get("question", "the meaning of all this suffering")
    prophecy = generate_prophecy(question)
    save_prophecy(prophecy)
    return jsonify(prophecy)

@app.route("/api/log")
def api_log():
    return jsonify(load_recent_prophecies())

if __name__ == "__main__":
    port = int(os.getenv("RELIC_ORACLE_PORT", 5008))
    print("╔════════════════════════════════════════════════════════════╗")
    print("║  THE RELIC ORACLE — THE COUNCIL AWAITS                     ║")
    print(f"║  http://localhost:{port}                                    ║")
    print("║  Ask. They will answer. You may not like it.               ║")
    print("╚════════════════════════════════════════════════════════════╝")
    app.run(host="0.0.0.0", port=port, debug=True)
